#############################################################################
# Makefile for building: qtmapper
# Generated by qmake (2.01a) (Qt 4.6.3) on: Tue Aug 10 17:33:13 2010
# Project:  qtmapper.pro
# Template: subdirs
# Command: /usr/bin/qmake -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile qtmapper.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-gui \
		sub-build

gui/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) gui/ || $(MKDIR) gui/ 
	cd gui/ && $(QMAKE) /Developer/Projects/qtmapper/gui/gui.pro -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o $(MAKEFILE)
sub-gui-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) gui/ || $(MKDIR) gui/ 
	cd gui/ && $(QMAKE) /Developer/Projects/qtmapper/gui/gui.pro -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o $(MAKEFILE)
sub-gui: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE)
sub-gui-make_default-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) 
sub-gui-make_default: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) 
sub-gui-make_first-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) first
sub-gui-make_first: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) first
sub-gui-all-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) all
sub-gui-all: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) all
sub-gui-clean-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-gui-clean: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-gui-distclean-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-gui-distclean: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-gui-install_subtargets-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) install
sub-gui-install_subtargets: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) install
sub-gui-uninstall_subtargets-ordered: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-gui-uninstall_subtargets: gui/$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) uninstall
build/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) build/ || $(MKDIR) build/ 
	cd build/ && $(QMAKE) /Developer/Projects/qtmapper/build/build.pro -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o $(MAKEFILE)
sub-build-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) build/ || $(MKDIR) build/ 
	cd build/ && $(QMAKE) /Developer/Projects/qtmapper/build/build.pro -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o $(MAKEFILE)
sub-build: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE)
sub-build-make_default-ordered: build/$(MAKEFILE) sub-gui-make_default-ordered  FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) 
sub-build-make_default: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) 
sub-build-make_first-ordered: build/$(MAKEFILE) sub-gui-make_first-ordered  FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) first
sub-build-make_first: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) first
sub-build-all-ordered: build/$(MAKEFILE) sub-gui-all-ordered  FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) all
sub-build-all: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) all
sub-build-clean-ordered: build/$(MAKEFILE) sub-gui-clean-ordered  FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) clean
sub-build-clean: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) clean
sub-build-distclean-ordered: build/$(MAKEFILE) sub-gui-distclean-ordered  FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) distclean
sub-build-distclean: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) distclean
sub-build-install_subtargets-ordered: build/$(MAKEFILE) sub-gui-install_subtargets-ordered  FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) install
sub-build-install_subtargets: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) install
sub-build-uninstall_subtargets-ordered: build/$(MAKEFILE) sub-gui-uninstall_subtargets-ordered  FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-build-uninstall_subtargets: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: qtmapper.pro  /usr/local/Qt4.6/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile qtmapper.pro
/usr/local/Qt4.6/mkspecs/common/unix.conf:
/usr/local/Qt4.6/mkspecs/common/mac.conf:
/usr/local/Qt4.6/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.6/mkspecs/qconfig.pri:
/usr/local/Qt4.6/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.6/mkspecs/features/qt_config.prf:
/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.6/mkspecs/features/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.6/mkspecs/features/debug.prf:
/usr/local/Qt4.6/mkspecs/features/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/x86.prf:
/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.6/mkspecs/features/warn_on.prf:
/usr/local/Qt4.6/mkspecs/features/qt.prf:
/usr/local/Qt4.6/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.6/mkspecs/features/moc.prf:
/usr/local/Qt4.6/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.6/mkspecs/features/resources.prf:
/usr/local/Qt4.6/mkspecs/features/uic.prf:
/usr/local/Qt4.6/mkspecs/features/yacc.prf:
/usr/local/Qt4.6/mkspecs/features/lex.prf:
/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile qtmapper.pro

qmake_all: sub-gui-qmake_all sub-build-qmake_all FORCE

make_default: sub-gui-make_default-ordered sub-build-make_default-ordered FORCE
make_first: sub-gui-make_first-ordered sub-build-make_first-ordered FORCE
all: sub-gui-all-ordered sub-build-all-ordered FORCE
clean: sub-gui-clean-ordered sub-build-clean-ordered FORCE
	-$(DEL_FILE) *.dylib
	-$(DEL_FILE) *.a
distclean: sub-gui-distclean-ordered sub-build-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-gui-install_subtargets-ordered sub-build-install_subtargets-ordered FORCE
uninstall_subtargets: sub-gui-uninstall_subtargets-ordered sub-build-uninstall_subtargets-ordered FORCE

sub-gui-check_ordered: gui/$(MAKEFILE)
	cd gui/ && $(MAKE) check
sub-build-check_ordered: build/$(MAKEFILE) sub-gui-check_ordered 
	cd build/ && $(MAKE) check
check: sub-gui-check_ordered sub-build-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

